const data = [
  {
    id: "01",
    img: "./assest/imgs/cello.jpg",
    alt: "cello",
    name: "Cello",
    info: "lorem iLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: "210",
  },
  {
    id: "02",
    img: "./assest/imgs/drum.jpg",
    alt: "drum",
    name: "Drum",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: "150",
  },
  {
    id: "03",
    img: "./assest/imgs/piano.jpg",
    alt: "piano",
    name: "Piano",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: "350",
  },
  {
    id: "04",
    img: "./assest/imgs/violin.jpg",
    alt: "violin",
    name: "Violin",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: "65",
  },
  {
    id: "05",
    img: "./assest/imgs/saxophone.jpg",
    alt: "saxophone",
    name: "Saxophone",
    info: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque.",
    price: "82",
  },
  {
    id: "06",
    img: "./assest/imgs/xylophone.jpg",
    alt: "xylophone",
    name: "Xylophone",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: "82",
  },
  {
    id: "07",
    img: "./assest/imgs/Guitar.jpg",
    alt: "Guitar",
    name: "Guitar",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: "40",
  },
  {
    id: "08",
    img: "./assest/imgs/Blue-Guitar.jpg",
    alt: "Blue Guitar",
    name: "Blue-Guitar",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: "240",
  },
  {
    id: "09",
    img: "./assest/imgs/Microphone.jpg",
    alt: "Microphone",
    name: "Microphone",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: "20",
  },
  {
    id: "10",
    img: "./assest/imgs/Headphones.jpg",
    alt: "Headphones",
    name: "Headphones",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: "10",
  },
  {
    id: "11",
    img: "./assest/imgs/Harp.jpg",
    alt: "Harp",
    name: "Harp",
    info: "loremLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quam velit, vulputate eu pharetra nec, mattis ac neque. ",
    price: "100",
  },
];

export default data;
